name: Testnet
env:
    OPERATOR_KEY: ${{ secrets.TESTNET_OPERATOR_KEY }}
    OPERATOR_ID: ${{ secrets.TESTNET_OPERATOR_ID }}
    HEDERA_NETWORK: "testnet"

defaults:
    run:
        shell: bash

permissions:
    contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: hiero-client-sdk-linux-medium
    steps:
      -   name: Harden Runner
          uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
          with:
            egress-policy: audit

      -   name: Setup GCC
          run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      - name: Set up Go 1.20
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Vet SDK and Examples
        run: go vet ./...

      - name: Build SDK and Examples
        run: go build -v ./...

  test:
    name: Test
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Setup GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      - name: Set up Go 1.19
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: go test -v -timeout 9999s

  golangci:
    name: lint
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
        with:
          version: v1.50
